devtools::install("ndimclusteringR")
library("ndimclusteringR")

print("Testing `join_matlist_on_name`")
test_join_matlist_on_name()
print("Testing `crop_matrices`")
test_crop_matrices()
print("Testing `convert_point_to_angle`")
test_convert_point_to_angle()
print("Testing `transform_coords_in_mat`")
test_transform_coords_in_mat()
print("Testing `rescale_by_end_col`")
test_rescale_by_end_col()
print("Testing `calc_member_dist_cent`")
test_calc_member_dist_cent()
print("Testing `find_closest_clust_snp`")
test_find_closest_clust_snp()
print("Testing `km_nan`")
test_km_nan()
print("Testing `clust_kmeans`")
test_cluster_kmeans()