devtools::install("ndimclusteringR")
library("ndimclusteringR")

print("Testing `join_matlist_on_name`")
test_join_matlist_on_name()
print("Testing `crop_matrices`")
test_crop_matrices()
print("Testing `convert_point_to_angle`")
test_convert_point_to_angle()
print("Testing `transform_coords_in_mat`")
test_transform_coords_in_mat()
